baseurl = "https://mircolosi.github.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Mirco Colosi"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[blackfriday]
  smartypants = false

[Params]
  subtitle = "Ph.D. Student"
  logo = "img/avatar-home.png"
  favicon = "resources/tri.png"
  dateFormat = "2 January 2006"
  commit = false
  rss = false
  comments = false



[Author]
  name = "Mirco Colosi"
  email = "colosi@diag.uniroma1.it,mirco.colosi@de.bosch.com"
  facebook = "mirco.colosi"
  gitlab = "mircolosi"
  github = "mircolosi"
  linkedin = "mirco-colosi"
  instagram = "lomerisa"
  spotify = "lomerisa"


[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About me"
    url = "about"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 3

[[menu.main]]
    name = "Contacts"
    url = "contacts"
    weight = 4


[[menu.main]]
    name = "Teaching"
    url = "teaching"
    weight = 3
